/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myDemoApp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    public void testFound() {
       ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 5));
       assertTrue(!App.search(array, 4, 5).isEmpty());
     }
 
     @Test
     public void testNotFound() {
       ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 5));
       assertFalse(App.search(array, 5, 7).isEmpty());
     }
 
     @Test
     public void testEmptyArray() {
       ArrayList<Integer> array = new ArrayList<>();
       assertTrue(App.search(array, 1, 10).equals("Your values are missing"));
     }
 
     @Test
     public void testNull() {
       assertTrue(App.search(null, 1, 1).equals("Your values are missing"));
     }

     @Test
     public void testItemMissing() {
       ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1,5));
       assertTrue(App.search(array, 0, 5).equals("You can\'t expect 0 number"));
     }
 
}
